# -*- coding: utf-8 -*-
"""Geometrical Shapes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18if1CljhzukWhDzrpp7OvYZ91OR08mL7
"""

length_of_side = int(input("Enter the length of one side: "))
def calcArea():
  Area_Hex=length_of_side*1.5*1.732
  print("Area of Hexagon is " ,Area_Hex )

def calcPeri():
  Perimeter_Hex=length_of_side*6
  print("Perimeter of Hexagon is " ,Perimeter_Hex )

def calcAngleSum():
  Angles_Hex=120*6   # 120 is the angle of one side of Hexagon
  print("Sum of all angles of Hexagon is " ,Angles_Hex )

def display():
  calcPeri()
  calcArea()
  calcAngleSum()

def calcAreaSquare():
  Area_Square=length_of_side*length_of_side
  print("Area of Square is " ,Area_Square )

def calcPeriSqaure():
  Perimeter_Square=length_of_side*4
  print("Perimeter of Square is " ,Perimeter_Square )

def display2():
  calcAreaSquare()
  calcPeriSqaure()



while True:

    User_Choice = int(input("Press 1 to display the Area, Perimeter, and Angles of Hexagon\nPress 2 to display the Area, Perimeter of Square\nPress any other key to Exit\n"))

    if User_Choice == 1:
        display()
    elif User_Choice == 2:
        display2()
    else:
        break  # Exit the loop if the user enters any other key